[config]
baseId = "base"
resourceId = "nouns"

[config.aliases]
name = "@base/properties/p-name"
description = "@base/properties/p-description"
instance-of = "@base/properties/p-instance-of"
subclass-of = "@base/properties/p-subclass-of"

[n-thing]
name = "Thing"

[n-intangible]
name = "Intangible"
subclass-of = "n-thing"

[n-role]
name = "Role"
subclass-of = "n-intangible"
description = "Represents additional information about a relationship or property. For example a Role can be used to say that a 'member' role linking some SportsTeam to a player occurred during a particular time period. Or that a Person's 'actor' role in a Movie was for some particular characterName. Such properties can be attached to a Role entity, which is then associated with the main entities using ordinary properties like 'member' or 'actor'."

[n-organization-role]
name = "Organization Role"
description = "A subclass of Role used to describe roles within organizations."
subclass-of = "n-role"

[n-repo-base]
name = "Base Repo"
description = "The base repository"

[n-person]
name = "Person"