[config]
baseId = "base"
resourceId = "properties"

[config.aliases]
d-string = "@base/data-types/d-string"
d-url = "@base/data-types/d-url"
d-noun = "@base/data-types/d-noun"

[n-property]
p-name = "Property"
p-instance-of = "n-property"

[p-name]
p-name = "Name"
p-instance-of = "n-property"
p-data-type = "d-string"

[p-description]
p-name = {value ="Description", id = "sdlkfjsdf"}
p-instance-of = "n-property"
p-data-type = "d-string"

[p-instance-of]
p-name = "Instance of"
p-inverse-name = "Instance"
p-data-type = "d-noun"
p-instance-of = "n-property"

[p-inverse-name]
p-name = "Name Inverse"
p-data-type = "d-string"
p-instance-of = "n-property"

[p-wikidata-id]
p-name = "Wikidata id"
p-description = "Id if on wikidata"
p-data-type = "d-string"
p-instance-of = "n-property"

[p-data-type]
p-name = "Data Type"
p-data-type = "d-noun"
p-inverse-name = "Is Data Type For"
p-instance-of = "n-property"

[p-aliases]
p-name = "aliases"
p-data-type = "d-string"
p-instance-of = "n-property"

[p-works-on]
p-name = "Works On"
p-description = "When noun works on things B."
p-data-type = "d-thing"
p-inverse-name = "Worked on by"
p-instance-of = "n-property"

[p-part-of]
p-name = "Part of"
p-data-type = "d-thing"
p-inverse-name = "Contains"
p-instance-of = "n-property"

[p-employed-by]
p-name = "Employed By"
p-data-type = "d-thing"
p-inverse-name = "Employs"
p-instance-of = "n-property"

[p-subclass-of]
p-name = "Subclass of"
p-data-type = "d-thing"
p-inverse-name = "Superclass of"
p-wikidata-id = "P279"
p-instance-of = "n-property"

[p-git-repo]
p-name = "Primary Git Repo"
p-data-type = "d-url"
p-inverse-name = "Is primary git repo of"
p-instance-of = "n-property"

[p-url]
p-name = "Url"
p-data-type = "d-url"
p-instance-of = "n-property"

[p-belongs-to]
p-name = "Belongs to"
p-data-type = "d-thing"
p-inverse-name = "Contains"
p-instance-of = "n-property"

[n-list]
p-wikidata-id = "Q12139612"
p-instance-of = "n-property"

[p-is-in-list]
p-name = "Is in list"
p-data-type = "d-thing"
p-inverse-name = "Contains"
p-instance-of = "n-property"

[p-was-autogenerated]
p-name = "Belongs to"
p-data-type = "d-noun"
p-inverse-name = "Contains"
p-instance-of = "n-property"

[p-official-website]
p-name = "Official Website"
p-wikidata-id = "P856"
p-data-type = "d-url"
p-instance-of = "n-property"

[p-image]
p-name = "Image (url)"
p-wikidata-id = "P18"
p-data-type = "d-image-url"
p-instance-of = "n-property"

[p-schemaorg-id]
p-name = "Schema.org ID"
p-instance-of = "n-property"
p-data-type = "d-string"

[p-parent-organization]
p-name = "Parent Organization"
p-schemaorg-id = "parentOrganization"
p-inverse-name = "Child Organization"
p-data-type = "d-noun"
p-instance-of = "n-property"

[p-twitter-username]
p-name = "Twitter Username"
p-description = "this item's username on Twitter; do not include the '@' symbol"
p-wikidata-id = "P2002"
p-data-type = "d-string"
p-instance-of = "n-property"

[p-github-username]
p-name = "Github Username"
p-description = "this item's username on Github"
p-data-type = "d-string"
p-instance-of = "n-property"

[p-lesswrong-username]
p-name = "LessWrong Username"
p-description = "this item's username on LessWrong"
p-data-type = "d-string"
p-instance-of = "n-property"

[p-effective-altruism-forum-username]
p-name = "Effective Altruism Forum Username"
p-description = "this item's username on the Effective Altruism Forum"
p-data-type = "d-string"
p-instance-of = "n-property"

[p-medium-username]
p-name = "Medium Username"
p-description = "this item's username on Medium"
p-data-type = "d-string"
p-instance-of = "n-property"

[p-linkedin-id]
p-name = "Linked Username"
p-description = "this item's username on Linked"
p-data-type = "d-string"
p-instance-of = "n-property"

[p-source-url]
p-name = "Source Url"
p-description = "this item's source Url"
p-data-type = "d-url"
p-instance-of = "n-property"

[p-data-source]
p-name = "Data Source"
p-inverse-name = "Data source for"
p-description = "A thing's data source"
p-data-type = "d-noun"
p-instance-of = "n-property"

[p-version]
p-name = "Version"
p-data-type = "d-string"
p-instance-of = "n-property"